version: '3.8'

services:
  # 1. flask app
  app:
    build:
      context: .
      target: final
    container_name: flask_app
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskdb
    networks:
      - front_net  # nginx
      - back_net   # db
    depends_on:
      - db
      - seed_runner
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # read-only
      - nginx_logs:/var/log/nginx
    networks:
      - front_net
    depends_on:
      - app
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net
  migration_runner:
    build:
      context: .
      target: final
    container_name: migration_runner
    restart: "no"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskdb
    networks:
      - back_net
    depends_on:
      db:
        condition: service_started
    command: >
      python -c "import time; 
      from src.app import create_app, db; 
      app = create_app(); 
      print('Czekam na start bazy...'); 
      time.sleep(5);
      with app.app_context(): db.create_all(); print('Migracje zako≈Ñczone sukcesem.')"

networks:
  front_net:
  back_net:

volumes:
  nginx_logs:
  db_data: