version: '3.8'

services:
  # 1. flask app
  app:
    build:
      context: .
      target: final
    container_name: flask_app
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskdb
    networks:
      - front_net  # nginx
      - back_net   # db
    depends_on:
      - db
      - seed_runner

networks:
  front_net:
  back_net: